### ISSUE TITLE
.gitignore

### ISSUE THREAD

**Issue by imin314** [AkhmadBabaev/fsd-landing#1]
Папку docs нужно добавить в .gitignore

**Comment by AkhmadBabaev** [comment]
Папка docs используется в качестве папки для github-pages.

**Comment by imin314** [comment]
Есть способ подгружать сорсы для github-pages из отдельной ветки

**Comment by AkhmadBabaev** [comment]
Согласен, но разве есть на это запрет ? И в итоге данная папка всё равно является залитой и занимает место в репозитории.

**Comment by imin314** [comment]
Запрета нет, но, чтобы поддерживать проект на github pages в актуальном состоянии после каждой итерации ревью, тебе нужно заново запускать build и отдельным коммитом заливать его в репозиторий, чтобы не смешивать его с коммитами по правкам. Зачем делать это вручную, если можно надежным способом разделить деплой и работу с сорсами проекта? 

Есть плагин gh-pages, который тебе поможет разворачивать проект на github-pages из другой ветки.

**Comment by AkhmadBabaev** [comment]
Окей, сделаю.
