### ISSUE TITLE
Деструктуризация объектов

### ISSUE THREAD

**Issue by imin314** [AkhmadBabaev/fsd-landing#10]
Нужно исправить глобально. Объекты рекомендуется деструктурировать:
https://github.com/AkhmadBabaev/fsd-landing/blob/914f7d88c052ec9b8a4206a58dae649abc9635ce/src/pages/colors/colors.pug#L26-L27

**Comment by AkhmadBabaev** [comment]
В чём заключается плюс деструктуризации в данный момент ? Инфомрация в data.json заточена под данный компонент, когда это не так я использую деструктуризацию но в данный момент я просто добавлю кода, а смысла никак не меняется.

**Comment by imin314** [comment]
Это просто общепринятая хорошая практика по стандартам airbnb, которые мы используем. Если бы в pug можно было добавить линтер с правилами airbnb, то он бы начал ругаться на эти строки.
Ничто тебе не мешает использовать деструктуризацию без добавления лишних строк: 
`const { colors, types } = require("./data.json");`

**Comment by AkhmadBabaev** [comment]
Я не верно тебя понял сперва. Поправлю.

**Comment by imin314** [comment]
Нужно поправить использование деструктуризации глобально по проекту. Вот здесь, например, явно можно получить из item title, type, content.
https://github.com/AkhmadBabaev/fsd-landing/blob/77f2e7e1423ed1719eae9f209fda8dbcff8ebbc9/src/components/ui-text-types/ui-text-types.pug#L12-L25
