### ISSUE TITLE
Именование и общие замечания по readability

### ISSUE THREAD

**Issue by imin314** [AkhmadBabaev/fsd-landing#12]
1. rgba() принято писать строчными буквами:
https://github.com/AkhmadBabaev/fsd-landing/blob/914f7d88c052ec9b8a4206a58dae649abc9635ce/src/components/card-data/card-data.scss#L12

2. Миксин hello() где-то используется? Если да, то надо ему дать более осмысленное название.
https://github.com/AkhmadBabaev/fsd-landing/blob/914f7d88c052ec9b8a4206a58dae649abc9635ce/src/components/card-info/card-info.scss#L1-L4

3. Названия классов должны описывать контент, который содержат элементы. Пока я не посмотрела готовую страницу, не могла понять, где используется компонент ui-types. Уж очень общие названия элементов в нем используются:
https://github.com/AkhmadBabaev/fsd-landing/blob/914f7d88c052ec9b8a4206a58dae649abc9635ce/src/components/ui-types/ui-types.pug#L8-L16

4. Мне кажется, схема с хранением класса блока в переменной приносит больше неудобств, чем выгоды. Визуально воспринимать БЭМ-структуру блока сложно, когда имя класса формируется через шаблонную строку, а в js-классе ты все равно не используешь переменную className.
https://github.com/AkhmadBabaev/fsd-landing/blob/914f7d88c052ec9b8a4206a58dae649abc9635ce/src/components/card/card.pug#L5-L9
Было бы проще, если бы общие классы добавлялись примерно так:
![Выделение_407](https://user-images.githubusercontent.com/40715953/83612751-0466e980-a5ad-11ea-8095-7e0cf2c8ef27.png)

**Comment by AkhmadBabaev** [comment]
1. rgba это зарезервированное слово в scss и прочих препроцессорах, для использования палитра из css надо написать RGB, HSL и т.д.

2. Hello видимо случайно забыл удалить это просто мусор при разработке.

3. Вероятно ты права, но даже не знаю как иначе это назвать, всё что в голову приходится выглядит абстрактно.

4. Касаемо визуально восприятия это сугубо личное потому что у меня как раз наоборот, это одна из причин такой структуры хотя если вся команда действует иначе нет проблем перестроиться. Так же когда мне надо переименовать компонент я не меняю его className и миксин. Хотя это мелочь конечно.

**Comment by imin314** [comment]
3. Класс все-таки лучше писать явно.
