### ISSUE TITLE
package.json

### ISSUE THREAD

**Issue by artamonJr** [AkhmadBabaev/fsd-landing#15]
Т.к. проект у тебя приватный, то нет необходимости в полях name, version и еще в некоторых. Это не критично, но тк ты добавил поле private, значит понимаешь о чем речь и можешь доработать эту идею до конца.

В этом файле имеется возможность использовать один скрипт внутри другого. Можешь ею воспользоваться, чтобы облегчить чтение кода
![image](https://user-images.githubusercontent.com/46949445/84659412-0bccb200-af20-11ea-981f-d2fd252af461.png)

Раскидай dep и devDep, руководствуясь [документом](https://docs.npmjs.com/specifying-dependencies-and-devdependencies-in-a-package-json-file)

**Comment by AkhmadBabaev** [comment]
Касаемо приватность, поле name используется в выводе консоли дев разработки, версия по сути не нужна, но я обычно делаю проект во время разработки приватным а так как не знаю что его ждёт в будущем я соблюдаю детали вроде версии.

**Comment by AkhmadBabaev** [comment]
Зависимости у меня вроде бы верно распределены, может я чего то не знаю не подскажешь ? На данный момент в dev разве что пакет chalk лишний.

**Comment by AkhmadBabaev** [comment]
Хотя этот проект как npm пакет вряд ли когда-то будет функционировать так что версию можно удалить, а вот остальное я оставлю.

**Comment by artamonJr** [comment]
Все отлично, остались зависимости.
Исходя из документации npm ""dependencies": Packages required by your application in production.", каким образом в продакшне у тебя используется, к примеру, pug?
Т.е. человеку, который скачал твой проект, используя npm install <package_name> нужен pug?

**Comment by AkhmadBabaev** [comment]
Если я правильно понимаю, то в dev должно быть то без чего продакшен не скомпилируется, у меня было ишью в слайдере с разделением зависимостей, так же с Сергеем обсуждал эту тему, вроде бы к правильному выводу пришел.

**Comment by AkhmadBabaev** [comment]
Если запустить команду **yarn dev** или **yarn start**  то в консоль выдает следующее 
![image](https://user-images.githubusercontent.com/51095975/84778831-35530f80-afec-11ea-8ae6-87b974af2286.png). Поле name берётся из package.json.

**Comment by AkhmadBabaev** [comment]
Касаемо зависимостей я так же думал как и ты вроде как. Поэтому до меня новая инфа долго доходила ) Хотя многие используют именно по предложенному тобой принципу. А та что нужна нам заключается в том что ты переносишь в dev только то что нужно чтобы запустить продакшен. К примеру твой репозиторий лежит где-то на сервере, а на сервере вряд ли ты будешь вести дев разработку, так что ты можешь удалить весь блок devDep и загрузить только то что нужно для компиляции продакшена.

**Comment by AkhmadBabaev** [comment]
Кстати я тоже кидал ссылку на документацию что и ты в качестве аргументов.

**Comment by artamonJr** [comment]
> Поле name берётся из package.json

Понял, ок)

> А та что нужна нам

Очень странно, что используется какая-то другая система распределения зависимостей. Только что проверил, мои знания верны по этому вопросу. Уточню этот момент тогда...

**Comment by AkhmadBabaev** [comment]
Окей
