### ISSUE TITLE
readme

### ISSUE THREAD

**Issue by artamonJr** [AkhmadBabaev/fsd-landing#16]
Запусти dev команду, зашел в браузере по адресу, который написан в файле (http://localhost) -> и что-то пошло не так(
![image](https://user-images.githubusercontent.com/46949445/84660712-ed67b600-af21-11ea-9657-65a7f942f8c3.png)
Исправь этот момент, не нужно вводить людей в заблуждение

**Comment by AkhmadBabaev** [comment]
Да верно, поправлю.
