### ISSUE TITLE
bugs/ui

### ISSUE THREAD

**Issue by artamonJr** [AkhmadBabaev/fsd-landing#17]
При запуске start команды, открывается страница номеров отеля. А как мне попасть на страницу цветов и шрифтов? Нужно организовать эту возможность

**Comment by AkhmadBabaev** [comment]
Это необходимо ? У меня была цель сделать страницу с номерами, а страницу цветов я просто дополнительно сделал и добавил ссылку на неё в ридме.,только для того чтобы показать больший обхват компонентов, само собой сделать индексную страницу с ссылками на номера и цвета могу, так же покопавшихся в репозиториях других ребят заметил что у многих такая тема.  То есть сомневаюсь что кто то с этим не справится )

**Comment by AkhmadBabaev** [comment]
Нашел время этим заняться, сверстал навигационную страницу под видом главной.

**Comment by artamonJr** [comment]
> У меня была цель сделать страницу с номерами, а страницу цветов я просто дополнительно сделал

Не знал, что это не входило в требования, извинтиляюсь) Но, что сделал, молодец. Стало намного удобнее

**Comment by artamonJr** [comment]
*Будешь ты менять body или добавлять контейнер дело твое) главное, чтобы проект соответствовал тех. заданию*
