### ISSUE TITLE
basic iteration(html, css, bem)

### ISSUE THREAD

**Issue by artamonJr** [AkhmadBabaev/fsd-landing#18]
В задании нет необходимости поддерживать IE, поэтому можно убрать это
![image](https://user-images.githubusercontent.com/46949445/84664777-b2688100-af27-11ea-8f10-e90ae2451fd9.png)

Можно чуть более описательный контент у тегов?
![image](https://user-images.githubusercontent.com/46949445/84665009-03787500-af28-11ea-9c07-a2c6dfb52ec1.png)

Использование капса - плохая практика, за исключение некоторых случаев
![image](https://user-images.githubusercontent.com/46949445/84665474-8d284280-af28-11ea-8062-e038140ef3e2.png)

Можно подумать о замене этого тега на более семантичный
![image](https://user-images.githubusercontent.com/46949445/84665918-1475b600-af29-11ea-8cc8-6eb6c14faa22.png)

Зачем ты поделил блок card на блоки? У тебя где-то используется этот блок не целиком?
![image](https://user-images.githubusercontent.com/46949445/84667594-40923680-af2b-11ea-9fb6-e2732dca1db1.png)

Тут тоже нужно поменять теги на семантичные
![image](https://user-images.githubusercontent.com/46949445/84666628-ffe5ed80-af29-11ea-879d-5712da7edc64.png)

Обязательно захламлять разметку ненужными тегами типа .card-data__separator?
![image](https://user-images.githubusercontent.com/46949445/84666862-4e938780-af2a-11ea-9ff6-6b756a5de0ff.png)

**Comment by AkhmadBabaev** [comment]
2. В бест практиках сказано что менеджер предоставит, так что смысл над этим париться в демо проекте.

3. Из за неудобного поведения функций препроцессора типа rbg и т.д. я стараюсь использовать функции CSS, для этого перевожу в капс.

4. Какой тэг там будет семантичен ?

5. Разве запрещено выносить в блок то что не используется где-то отдельно ? Я создал эти блоки чтобы меньше мучаться с именованием и не делать блок слишком большим.

**Comment by AkhmadBabaev** [comment]
6. Атрибуты tabindex, role, aria-label добавляет swiper-slider, див с ролью button уже равносилен тэгу button, то есть семантика не нарушается но если я сделаю заменю div на button я получу button с ролью button.

**Comment by artamonJr** [comment]
> Из за неудобного поведения функций препроцессора типа rbg и т.д. я стараюсь использовать функции CSS, для этого перевожу в капс.

Эмм, а чем отличается rgb function в scss от css?

> Разве запрещено выносить в блок то что не используется где-то отдельно ? Я создал эти блоки чтобы меньше мучаться с именованием и не делать блок слишком большим.

Посмотрел еще раз. Правильно, что выделил рейтинг, цену в отдельный компоненты, но вот, к примеру, тут, явно это не блоки. Блок - независимая часть страницы, которая может быть повторно использована. Не думаю, что card-data где-то пригодится
![image](https://user-images.githubusercontent.com/46949445/84781090-0ee2a380-afef-11ea-9e2f-d9af6424f32a.png)

> Атрибуты tabindex, role, aria-label добавляет swiper-slider

Уже не добавляет) Окей, если role будет добавлять, то можно оставить
![image](https://user-images.githubusercontent.com/46949445/84782210-6df4e800-aff0-11ea-9b6a-853e24453005.png)

> Разве запрещено выносить в блок то что не используется где-то отдельно ?

Нет конечно. Но выносить то, что в принципе не может использоваться отдельно, запрещено.

Тут cards-list нет смысла выделять в отдельный блок, тк он не может использоваться независимо.
![image](https://user-images.githubusercontent.com/46949445/84782605-e8256c80-aff0-11ea-9dd5-554e39a8989f.png)

По стандартам, не стоит задавать картинки одновременно width и height
![image](https://user-images.githubusercontent.com/46949445/84782887-481c1300-aff1-11ea-93e1-b40b2d0ad870.png)

Не работает рейтинг и переключение слайдов, нету пагинации у номера. Это у меня только?

Подбери правильный alt для картинки
![image](https://user-images.githubusercontent.com/46949445/84783213-aa751380-aff1-11ea-961e-7e0acdcb44a3.png)

Вот тут нельзя упростить, убрав псевдоэлементы?
![image](https://user-images.githubusercontent.com/46949445/84783746-39822b80-aff2-11ea-80bd-ff6a77d35c2c.png)
![image](https://user-images.githubusercontent.com/46949445/84783882-57e82700-aff2-11ea-8700-82da6af73f5c.png)

Звездный рейтинг? Может лучше просто rating?
![image](https://user-images.githubusercontent.com/46949445/84783530-0f306e00-aff2-11ea-8406-aa10784eec41.png)

Не смешивай разметку и стили. Тег b чисто декоративный элемент, без семантики, абсолютно. Для декорации у нас есть css
![image](https://user-images.githubusercontent.com/46949445/84783940-68000680-aff2-11ea-979b-90875e185581.png)

**Comment by AkhmadBabaev** [comment]
Отличие в том что rbg препроцессоров обычно компилирует результат в модель HEX, то есть я объявляю rbg получаю hex, это доставляет проблем когда ты пытаешься использовать css переменные внутри rbg, hsl препроцессоров, вылетают ошибки, а нативные аналоги css позволяют взаимодействовать даже с scss. По этой причине я использую нативные варианты так как их поведение является понятным.

**Comment by AkhmadBabaev** [comment]
> Не работает рейтинг и переключение слайдов, нету пагинации у номера. Это у меня только?
Виноват, в последний правках js не подключил, поправлю.

**Comment by AkhmadBabaev** [comment]
> Звездный рейтинг? Может лучше просто rating? 

Сперва хотел так и написать, покопавшись в инете нашел что это называется звездный рейтинг, схемы рейтинга могут быть разные так что по смыслу такое название самое понятное.

**Comment by AkhmadBabaev** [comment]
> По стандартам, не стоит задавать картинки одновременно width и height

На самом деле видел такую схему, я даже думаю ишью создать в best practice по этому поводу, так что не против если оставим эту тему. Я просто учту это на будущее.

**Comment by AkhmadBabaev** [comment]
> Не смешивай разметку и стили. Тег b чисто декоративный элемент, без семантики, абсолютно. Для декорации у нас есть css

Вот тут не совсем понял. Да этот тег декоративный поэтому я выбрал его вместо strong, просто чтобы избавиться от лишней css строки типа font-weight bold. В ином случае надо ставить span и добавлять стиль, а так короче выходит, и по стандартам не запрещено.

**Comment by AkhmadBabaev** [comment]
> Вот тут нельзя упростить, убрав псевдоэлементы?

Псевдо-элементы в данном случае берут на себя центрирование, так что даже если их брать то надо тэг создавать и ему имя придумывать, но ещё более важно то как я использую иконки, попробовав пару вариантов, вариант с передачей строки в свойство content псевдо-элемента показался мне самым удобным.

**Comment by artamonJr** [comment]
> Отличие в том что rbg препроцессоров обычно компилирует результат в модель HEX, то есть я объявляю rbg получаю hex, это доставляет проблем когда ты пытаешься использовать css переменные внутри rbg, hsl препроцессоров, вылетают ошибки, а нативные аналоги css позволяют взаимодействовать даже с scss

Не знал, спасибо)

> На самом деле видел это в best практиках, я даже думал ишью создать в best practice по этому поводу, так что не против если оставим эту тему. Я просто учту это на будущее.

На самом деле, не понял сути того что ты сказал) Не исправил

> Вот тут не совсем понял. Да этот тег декоративный поэтому я выбрал его вместо strong, просто чтобы избавиться от лишней css строки типа font-weight bold. В ином случае надо ставить span и добавлять стиль, а так короче выходит, и по стандартам не запрещено.

Не нужно опираться исключительно на стандарты, в стандартах невозможно описать всех вещей. 
Смешение разметки со стилями считается плохой практикой, тк для стилей был придуман css(это раз). Если тебе нужно будет покрасить цвет текста в красный, то ты пойдешь в стили и напишешь ту самую "не нужную" для тебя строчку кода. А потом, наверняка, будешь переписывать тег b на span, чтобы перенести этот font-weight в стили

Остальные вопросы оставим, не так важнО это. Я лишь дал пищу для размышлений)

Посмотри повнимательнее, правильно ли тут все?)
![image](https://user-images.githubusercontent.com/46949445/85032498-97487c00-b188-11ea-9214-cfed4a484e49.png)

**Comment by AkhmadBabaev** [comment]
> На самом деле, не понял сути того что ты сказал) Не исправил

Я хочу сказать что это правило не верное или даже устаревшее, я создам ишью в будущем по этому поводу в best-practice и попросил оставить это как есть.

**Comment by artamonJr** [comment]
Почему при инициализации страницы у последней звезды добавляется модификатор?
![image](https://user-images.githubusercontent.com/46949445/85129018-172f1e80-b23b-11ea-886f-4f78d80b495e.png)

Count - verb, нужно изменить название
![image](https://user-images.githubusercontent.com/46949445/85129070-2ca44880-b23b-11ea-8a89-b636ff88e760.png)

**Comment by AkhmadBabaev** [comment]
> Почему при инициализации страницы у последней звезды добавляется модификатор?

Этот модификатор определяет активную звезду, то есть если рейтинг 5, то последняя горящая звезда будет 5, а с помощью css сделано так чтобы все следующие звёзды не горели.

**Comment by artamonJr** [comment]
Inner - adjective, поправь
![image](https://user-images.githubusercontent.com/46949445/85132724-0504ae80-b242-11ea-8d18-a4a70d194b88.png)

Не используй inline стили
![image](https://user-images.githubusercontent.com/46949445/85133192-ece15f00-b242-11ea-88e4-e0344bab0a25.png)

Как тут переводится head?
![image](https://user-images.githubusercontent.com/46949445/85133520-83ae1b80-b243-11ea-8ecc-37e2b8e71d46.png)

**Comment by AkhmadBabaev** [comment]
> Как тут переводится head?

Голова.

**Comment by AkhmadBabaev** [comment]
> Не используй inline стили

Обычно я стараюсь избегать инлайн стилей но в данном случае удобнее их использовать вместо того чтобы создавать кучу классов и обрабатывать эти модификаторы цвета в pug. К тому же так или иначе в этот компонент мы передаем значение и выводим его рядом с блоком, не проще ли использовать это значение в инлайн стилях как это сделал я ?

**Comment by artamonJr** [comment]
> не проще ли использовать это значение в инлайн стилях как это сделал я ?

Я уже говорил, что html отдельно, css отдельно. Это разделение не с проста было создано и его желательно не нарушать. И + этим ты нарушаешь наши стандарты.

В случае, когда у компонента много разных тем оформления, лучше воспользоваться модификатором ключ-значение. Так будет намного нагляднее и в scss файле удобнее обрабатывать.
![image](https://user-images.githubusercontent.com/46949445/86138654-686ec600-baf7-11ea-946c-b1839b458fb3.png)

**Comment by AkhmadBabaev** [comment]
> Серьезно?) Придумай другое название 

А в чём тут проблема ?

**Comment by AkhmadBabaev** [comment]
Ах да, title уже занят.

**Comment by AkhmadBabaev** [comment]
Может переименовать элемент **head** в **item** , а элемент **content** в "example" ?
