### ISSUE TITLE
project structure

### ISSUE THREAD

**Issue by artamonJr** [AkhmadBabaev/fsd-landing#19]
Обычно, эту папку именуют webpack
![image](https://user-images.githubusercontent.com/46949445/85133835-223a7c80-b244-11ea-886a-6b67e2f963fc.png)

Какую роль в проекте у тебя имеют эти файлы?
![image](https://user-images.githubusercontent.com/46949445/85133855-2c5c7b00-b244-11ea-8a31-f489a051f469.png)

Фото номеров не общие для всего проекта, а поэтому должны лежать в папке компонента
![image](https://user-images.githubusercontent.com/46949445/85133941-56ae3880-b244-11ea-8ecf-2ba0dae53461.png)

**Comment by AkhmadBabaev** [comment]
> Какую роль в проекте у тебя имеют эти файлы?

Отмена индексации и уже настроенное кэширование это просто из шаблона задел на будущее. На сервере .htaccess пригодится а robot.txt во время разработки.

**Comment by AkhmadBabaev** [comment]
Чтобы было меньше вопросов папку public удалил )

**Comment by artamonJr** [comment]
> Чтобы было меньше вопросов папку public удалил )

Можно было оставить, я просто спросил)

> Это очень субъективная правка, мне предпочтительнее название config

Config может быть чего угодно просто, а название webpack сразу понятно для чего) Хорошо, оставь
