### ISSUE TITLE
readme

### ISSUE THREAD

**Issue by imin314** [AkhmadBabaev/fsd-landing#2]
В readme нужно добавить команды для запуска devserver, сборки и развертывания проекта.

**Comment by AkhmadBabaev** [comment]
![image](https://user-images.githubusercontent.com/51095975/83613290-3caa0000-a58c-11ea-8670-e8aa9e0aea6b.png)
А вот это разве не годится ?

**Comment by imin314** [comment]
Да, извиняюсь, что не заметила их. Когда разберешься с github-pages тогда из первого ишьюза, надо будет еще добавить команду для деплоя.
