### ISSUE TITLE
detailed iteration (html/pug, css/scss, bem, js)

### ISSUE THREAD

**Issue by artamonJr** [AkhmadBabaev/fsd-landing#20]
Почему тут не использовать относительные пути в ссылках?
![image](https://user-images.githubusercontent.com/46949445/85135379-ac83e000-b246-11ea-8a7b-f2d04ed54f8a.png)

По-хорошему, нужно писать самодокументируемый код, когда это возможно. Бывают случаи, когда код ну очень сложен и никакие техники для документации кода не действуют(e.g. хорошие имена переменных), тогда можно добавить комментарии, но делать это тоже очень внимательно. У тебя очень простой код и комментарии тут избыточны)
![image](https://user-images.githubusercontent.com/46949445/85135808-60856b00-b247-11ea-8531-1d24ed4d2375.png)

Не согласен, что это главный цвет. Главный цвет - basic-color у тебя. Нужно переименовать
![image](https://user-images.githubusercontent.com/46949445/85136326-25d00280-b248-11ea-9267-155fb56b68e6.png)

Использование этого цвета не нашел
![image](https://user-images.githubusercontent.com/46949445/85136396-3c765980-b248-11ea-81a7-a470026b5d35.png)

Удалить пустые строчки, кроме последней
Все цвета вынести в константы
Почему такой line-height выбран?
Зачем отключил kerning шрифтов?
Насчет 10-ой [строчки](https://developer.mozilla.org/en-US/docs/Web/CSS/-webkit-tap-highlight-color) + не используй important
![image](https://user-images.githubusercontent.com/46949445/85136539-6def2500-b248-11ea-96b3-6fbc87db4d67.png)

**Comment by AkhmadBabaev** [comment]
Почему тут не использовать относительные пути в ссылках? 

При разработке так удобнее. Всё таки вебпак алиасы позволяют. А на выходе всё равно путь от корня идёт а в корне все html файлы лежат.

**Comment by AkhmadBabaev** [comment]
> У тебя очень простой код и комментарии тут избыточны. 

С тем что они избыточно согласен, я на будущее сделал задел, при компиляции всё равно удаляется.

**Comment by AkhmadBabaev** [comment]
> Использование этого цвета не нашел 

Да он вроде как не пригодился, удалю.

**Comment by AkhmadBabaev** [comment]
> Почему такой line-height выбран 

Пробежался по макету выбрал его как общий что тут сказать.

**Comment by AkhmadBabaev** [comment]
> Удалить пустые строчки, кроме последней

А это правило откуда ? Стайл гайд мб у меня такой )

**Comment by AkhmadBabaev** [comment]
> Насчет 10-ой строчки + не используй important 

Ранее не работало без important видимо где-то ошибся, уберу.

**Comment by AkhmadBabaev** [comment]
Зачем выносить все цвета в константы ? под все подразумеваются и те что используются единожды.

**Comment by AkhmadBabaev** [comment]
> Не согласен, что это главный цвет. Главный цвет - basic-color у тебя. Нужно переименовать

Обычно главным цветом выделяют цвета призванные сделать акцент на чём либо, так называемые доминанты, показываю удобство такого разделения цветов при смене цвета доминанта. Что касается переменной basic-color она обхватывает цвета текста, рамок - такие переменные не будет кардинально меняться типа в красный цвет или подобное, в примерах эти переменные называют типографическими, я решил назвать basic так как всё таки не только текст но и рамки идут во внимание. Тема достаточно сложная сомневаюсь что кто-то из нас может с уверенностью утверждать. 

[Материал](https://material.io/design/color/the-color-system.html#color-theme-creation)

**Comment by artamonJr** [comment]
> С тем что они избыточно согласен, я на будущее сделал задел, при компиляции всё равно удаляется.

Это да, но код то твой будет читаться людьми. И, по-моему, можно догадаться, где цвета, а где шрифт и без многострочных комментариев

Комментарии так и не убрал. Зачем тут комментарий "basic"? Как он помогает читать код?
![image](https://user-images.githubusercontent.com/46949445/86141088-4f1b4900-bafa-11ea-84ae-3522bf53720d.png)

>  Тема достаточно сложная, сомневаюсь что кто-то из нас достаточно в этом разбирается, предлагаю оставить как есть.

Во-первых, ребята в mui разделяют так, ребята в другой команде по-другому. Но ориентироваться на более опытных коллег конечно же нужно. Но ты не правильно понял их концепцию походу. Я мельком глянул и вот что они пишут по primary-color:
![image](https://user-images.githubusercontent.com/46949445/86142114-82aaa300-bafb-11ea-86d4-9a15014b6c5e.png)
Я с этим полностью согласен. Очень странно иметь primary и basic, они как бы идентичны)

По этому св-ву я скинул ссылку. Ты читал?
![image](https://user-images.githubusercontent.com/46949445/86142930-7541e880-bafc-11ea-8589-c4d4c965dfc5.png)

> придумывание имён переменным и препроцессор на обработку этих переменных

Придумывание имени белому цвету? И что ты собрался делать с препроцессором?

> UI цвета обычно те что переиспользуются в проекте, такие я выношу в переменные

![image](https://user-images.githubusercontent.com/46949445/86143198-d073db00-bafc-11ea-9ca3-dfd8154000c0.png)

**Comment by AkhmadBabaev** [comment]
> Комментарии так и не убрал. Зачем тут комментарий "basic"? Как он помогает читать код? 

Мне помогает, очень субъктивная тема.

> Во-первых, ребята в mui разделяют так, ребята в другой команде по-другому. Но ориентироваться на более опытных коллег конечно же нужно. Но ты не правильно понял их концепцию походу. Я мельком глянул и вот что они пишут по primary-color:

Видимо каждый понимает как хочет но ты обрати внимание на примеры, они не выделяют базовый цвет текста в primary, под primary подразумевается главный цвет темы а не вообще сайта.

> По этому св-ву я скинул ссылку. Ты читал? 

Что я там должен был найти ?

> Придумывание имени белому цвету? И что ты собрался делать с препроцессором?

Какой смысл создавать переменную белый цвет ? Потом когда я в боди меняют цвет на красный, я создаю переменную красный цвет. По смыслу эти переменные никак не связаны то есть они не должны меняться повсюду разом на сайте, все что по смыслу связанно выделяется в доминанты. Я просто на создаю переменных от которых я не получу пользы в переиспользовании, так что затрачу время а препроцессор тратит время на компляцию и присваивание.

**Comment by artamonJr** [comment]
> Для нормализации поведения при клике во всех браузерах его стоит убрать

Окей, оставляем. Разобрался я для чего оно)

Удали 13 строчку)
И переменную лучше вынести в variables
![image](https://user-images.githubusercontent.com/46949445/86214884-7c143e00-bb84-11ea-8a1d-93b355b7f5db.png)

Лучше все-таки использовать аргумент path в миксине, чтобы при использовании этого миксина, можно было прокидывать относительный путь к шрифту. А сейчас у тебя в миксине обрабатывается путь относительно корня. А что если у тебя миксины переедут в другую папку?
И почему 2 св-ва src сделал? Можно же одним обойтись
![image](https://user-images.githubusercontent.com/46949445/86215415-399f3100-bb85-11ea-9f84-c00540023cc2.png)

Использование переменных должно быть явным, поэтому нужно заимпортить variables
![image](https://user-images.githubusercontent.com/46949445/86215833-c2b66800-bb85-11ea-8d01-98207e258a83.png)

Почему бы не убрать width и оставить min-width и max-width, поменяв значения?
![image](https://user-images.githubusercontent.com/46949445/86215958-f2fe0680-bb85-11ea-87e3-a038069125a1.png)

Зачем тут шрифт montserrat? Он не используется в этом файле) Тут просто объявления переменных
![image](https://user-images.githubusercontent.com/46949445/86217163-bdf2b380-bb87-11ea-821e-757a099fc27a.png)

Есть возможность вынести эту логику в webpack config? Это не совсем к месту в pug файле
![image](https://user-images.githubusercontent.com/46949445/86218183-1f675200-bb89-11ea-939c-b2c572735ed1.png)
![image](https://user-images.githubusercontent.com/46949445/86218224-28f0ba00-bb89-11ea-965e-04f4869e8357.png)
![image](https://user-images.githubusercontent.com/46949445/86218269-373ed600-bb89-11ea-8c87-66b01e321e69.png)

Пройтись по всем файлам и оставить только одну пустую строчку в конце
![image](https://user-images.githubusercontent.com/46949445/86218434-70774600-bb89-11ea-94b1-31dd1df04dcb.png)

Форматирование дело вкуса конечно, но вот отступ на 16 строчке немного странный. Ты в html файле дробишь каждый элемент отступами? Мне кажется, было бы лучше убрать отступы из разметки между тегами
![image](https://user-images.githubusercontent.com/46949445/86218794-fbf0d700-bb89-11ea-9e08-4c2f10214d35.png)

> Как говорил ранее базовый цвет текста называют typography так что раз так смущает basic заменю на typography

Подумал по этому поводу и, соглашусь с тобой. Разумно ты разделил basic и primary. Если хочешь, можешь вернуть на basic

Размещение css правил должны соответствовать размещению тегов в разметке. Поэтому на 7 строчке должно быть правило для container'а
![image](https://user-images.githubusercontent.com/46949445/86219197-8802fe80-bb8a-11ea-8e73-404f7c6b310a.png)

Эти данные относятся к другим компонентам, поэтому лучше разделить их и разнести по компонентам
![image](https://user-images.githubusercontent.com/46949445/86219746-46268800-bb8b-11ea-866a-c430fb44f72b.png)

Жесть, ты переусложнил конечно)
Можно, минуя boxColorsModifiers, прокидывать в массив классов, в ключ color, сразу color из аргумента?
И аргумент opacity у тебя не используется нигде
![image](https://user-images.githubusercontent.com/46949445/86221231-50498600-bb8d-11ea-92cd-d1a7a1793ce7.png)

Тут тоже нужен явный импорт variables
![image](https://user-images.githubusercontent.com/46949445/86221367-7f5ff780-bb8d-11ea-9fb2-3ead9a1aa385.png)
![image](https://user-images.githubusercontent.com/46949445/86222028-5ab84f80-bb8e-11ea-8b6a-74e326cd0180.png)

По умолчанию у box не должно быть background. Он регулируется модификаторами
![image](https://user-images.githubusercontent.com/46949445/86221576-bafac180-bb8d-11ea-9d0b-b795c52a6fc2.png)

Тут тоже слишком сложная логика по созданию классов для такой просто операции
Ты выделил в отдельный файл данные для этого компонента(это молодец, кстати:)) и в этом файле у тебя уже есть поле type, которое ты можешь использовать у себя в компоненте.
![image](https://user-images.githubusercontent.com/46949445/86222342-c7cbe500-bb8e-11ea-9cfe-7401d77a04a6.png)

Тут можно упростить, повесив на main класс .container и избавившись от второго container'а. Сейчас у тебя обертка внутри другой обертки)
![image](https://user-images.githubusercontent.com/46949445/86222781-5b051a80-bb8f-11ea-9eca-680ba3bafa1b.png)

**Comment by AkhmadBabaev** [comment]
> Лучше все-таки использовать аргумент path в миксине, чтобы при использовании этого миксина, можно было прокидывать относительный путь к шрифту. А сейчас у тебя в миксине обрабатывается путь относительно корня. А что если у тебя миксины переедут в другую папку?

Ты имел ввиду наоборот, типа в миксине относительный путь а желательно от корня ?

**Comment by AkhmadBabaev** [comment]
> И почему 2 св-ва src сделал? Можно же одним обойтись

Скорее всего, если я не ошибаюсь это программа конвертации шрифтов выдавала такую структуру я решил не вдаваться в детали и оставить как есть. Поправлю.

**Comment by AkhmadBabaev** [comment]
> Использование переменных должно быть явным, поэтому нужно заимпортить variables

Сейчас я импортирую переменные в basic.scss, а basic.scss служит основой всем файлам, есть ли необходимость явно импортировать variables.scss везде, с учётом того что variables.scss уже поставляется везде ?

**Comment by AkhmadBabaev** [comment]
> Форматирование дело вкуса конечно, но вот отступ на 16 строчке немного странный. Ты в html файле дробишь каждый элемент отступами? Мне кажется, было бы лучше убрать отступы из разметки между тегами

У меня нет четких правил разделения элементов, я ставлю пробелы если считаю что так глазу будет читабельнее, если я уберу пробелы для меня читаемость ухудшится.

**Comment by AkhmadBabaev** [comment]
> Есть возможность вынести эту логику в webpack config? Это не совсем к месту в pug файле

К сожалению нет или я не нашел, а с **webpack** дружу достаточно хорошо.

**Comment by AkhmadBabaev** [comment]
> Зачем тут шрифт montserrat? Он не используется в этом файле) Тут просто объявления переменных

Решил что раз montserrat является базовым шрифтов то есть для всего проекта решил установить его рядом с местом где его объявляю, хотя ты прав ему там не место. Перенесу в basic.

**Comment by AkhmadBabaev** [comment]
> Эти данные относятся к другим компонентам, поэтому лучше разделить их и разнести по компонентам

Если предположить что этот компонент с другими данными будет использоваться уже простой итерацией не обойтись так как всё будет в кучу, чтобы этого избежать нужно будет создавать свойства в data.json отдельно для каждого компонента где будут данные только для этого компонента. В текущем варианте, создаешь данные которые используешь в этом текущем компонент, а так же импорт data.json с текущего каталога  вместо **"../ui-color/data.json"**.

**Comment by AkhmadBabaev** [comment]
> Тут тоже слишком сложная логика по созданию классов для такой просто операции
Ты выделил в отдельный файл данные для этого компонента(это молодец, кстати:)) и в этом файле у тебя уже есть поле type, которое ты можешь использовать у себя в компоненте.

Я может не верно тебя понял, что касается способа работы с модификаторами то я последовал [ишью](https://github.com/AkhmadBabaev/fsd-landing/issues/13).

**Comment by artamonJr** [comment]
> Ты имел ввиду наоборот, типа в миксине относительный путь а желательно от корня ?

Ой, да. Обычно, в БЭМ компоненте делаются относительные ссылки, к примеру из scss файла, к картинке. Этим сохраняется независимость БЭМ компоненты. Т.е. ты ее можешь спокойно выдернуть из проекта и вставить в другом проекте и ничего не нужно будет править. А в других файлах, к примеру как в этом миксине, лучше делать пути от корня, типо src/folder-name/file-name

На 7 строчке желательно указать формат шрифта. Это подсказка браузеру, какой шрифт загружать. Браузер смотрит на формат шрифта и решает, может ли он его загрузить или нет, если нет, то двигается к следующему шрифту, без ненужной загрузки того шрифта, который он не может обработать.
![image](https://user-images.githubusercontent.com/46949445/86323439-83e7e700-bc45-11ea-848c-fe6d645797bf.png)

> есть ли необходимость явно импортировать variables.scss везде, с учётом выше сказанного?

Я тоже задавался себе этим вопросом)) Я решил, что так будет более наглядно, тк сразу видно все зависимости компоненты. Ну и у нас в стандартах по этому поводу есть пункт, про то, что все зависимости явно должны быть указаны.

> если я уберу пробелы для меня читаемость ухудшится.

Ну окей, оставим, дело субъективное. Стилизация кода, все равно будет навязываться тебе eslint и stylint в проектах)

> К сожалению нет или я не нашел, а с webpack дружу достаточно хорошо

Хорошо, оставим

> Я может не верно тебя понял, полагаю ты имел ввиду, что можно написать короче, объявить модификаторы прям на месте как к примеру я отрефакторил компонент ui-color по твоей правке. Касаемо модификаторов в компоненте ui-text-types то я следовал ишью

Да, в ui-color сделал хорошо. Issue глянул, было у тебя действительно хардкорно) Но и вариант, который коллега предложила, для меня тоже слишком сложный для такой простой операции.
Ты сам как считаешь, какой вариант проще и нагляднее?

**Comment by AkhmadBabaev** [comment]
> Ты сам как считаешь, какой вариант проще и нагляднее?

Я думаю там где у нас 1-2 модификатора твой вариант будет лучше, при большем количестве модификаторов то я бы предпочёл вариант Ирины. Я мог сразу поменять на твой вариант так как и в компонент ui-text-types твой вариант будет удобнее, но если буду работать в компании при ревьювинге будет не плохо иметь оба варианта (с объяснением в виде наших комментов) чтобы студент мог подсмотреть на моём шаблоне что ему надо делать. Поэтому предлагаю оставить как есть.

**Comment by AkhmadBabaev** [comment]
И так, пришлось вернуть относительный путь в mixin font-face так как иначе в продакшене пути ломаются.

> По этому пункту, может ты меня неправильно понял, но я имел ввиду colors вынести в компонент ui-colors-list, а types в ui-text-types

Представь что компонент ui-color-list использую на другой странице с другими данными, получится у меня в json файле что-то вроде, ui-color-page и его данные и пусть будет room-filter-page и данные которые принадлежат этой странице. Чем больше страниц где я переиспользую данные компонента тем больше и не сложнее будет становиться мой json файл. Я понимаю что по логике можно подумать что данные о цветах ui-color-list но на самом деле он рассчитан на переиспользование и получение данных из вне, такая же ситуация с ui-text-types и подобными компонентами.

> Переменную в variables

Переменная намеренно была создана там, так как это локальная переменная, так как в других компонентах её использование не планируется я просто зря буду увеличивать файл variables (который и без того много куда подключен) такими локальными переменными. Если переменная станет глобальной то вынести её и переименовать на более глобальное имя не проблема.

> Зачем height?

Ранее рассказывал о том что после сдачи проекта мы уже не контролируем изображения что устанавливает клиент, если не ограничить размеры карточки, то изображения разного размера могут растягивать карточку, даже если попросить клиента быть осторожным или на сервере какой-то плагин будет обрезать изображения под размеры карточек, то завтра мы решим изобржаения под ретина подгружать размеры которых будут больше чем ширина высота карточки.

> Также, странный background у кнопки. Зачем там третий цвет, начиная с 99.9%?) Его же никто не увидит
Также, z-index можно сделать 2, тк выше у элемента он установлен в значение 1

На счёт бэграунда тут я просто скопировал с figma макета и вставил, а так да ты прав. Z-index я поправил но я намеренно установил 10. Если по порядку нумеровать z-index можно обжечся, так как повышение уровня нижнего слоя заставит нас повысить все остальные, поэтому легче ставить разрыв около 5-10 между слоями, так и новые легко вставишь если что.

> Зачем тут каскад?

Для повышения специфичности селектора иначе swiper-pagination перебивает его свойства.

> Убери св-ва, которые перебивает swiper-pagination

Скорее всего ты убрал каскад поэтому у тебя и перебивает.

И почему pointer-events отключил?

Отключил чтобы клик не срабатывал, а сейчас вспомнил что обработка клика включается в опциях swiper-plugin и я её отключил уже давно, так что pointer-events уже не нужен.

> Зачем тут position и overflow?

overflow для корректной работы скругленных рамок, а position уже не нужен.

> Это перенеси просто в футер плиз

Присмотрись внимательно, если перенесу то работать уже будет иначе.

> Удали 14 строку, это правило у тебя с 3 строки подтягивается

Не подтягивается )

> Не пойму, как эти пути парсятся? Относительно чего?

Относительно корня папки docs, знаю звучит сложно но пока так, может когда-нибудь обновят pug-loader и ему подобные для норм работы импортов. Вероятно есть вариант как это исправить даже сейчас но я без понятий, провозился с этим ранее много.

> При рейтинге 0 у номера, твоя логика ломается
Также, это элементы по которым мы нажимаем, поэтому нужно подобрать семантический тег
И почему ты отключил tabindex?

И так, tabindexя как раз наоборот установил, семантических тэг не подходит так как это скорее всего будет input ratio, но чтобы бы не было это кнопки а кнопки по стандартам в форму. Рейтинг обычно много где встречается к примеру в отзывах рядом с комментариями, иными словами сам рейтинг может быть частью другой формы а по стандартам форму в форму вкладывать нельзя. 

> Логику по добавлению слушателей нужно вынести в init

Логика добавления слушателей и так в init, а это привязка контекста, привязка контекста идёт от constructora то есть даже если переносить все привязки контекста в другие функции стоит отметить что потом эти функции надо будет привязать к конструктору.

> Смотри какой раздутый у тебя получился обработчик клика. В нем ты и проверяешь, что клик был сделан по звезде, и добавляешь модификатор(единственное действие, которое нужно делать) и убираешь модификатор со всех звезд. Нужно определенно упростить этот метод, убрав делегирование событий

Как по мне он получился в самый раз, один клик, удаление другие модификаторов (если у тебя не input ratio иначе никак). А делегирование как раз в таких моментах и полезно, вместо привязки обработчика клика каждой из звёзд я обращаюсь только к родителю.

> Можешь назначение вот этого объяснить?

Этот код обрабатывает нажатие клавиши enter(если фокус на элементе) как клик, то есть имитирую поведение кнопки.

**Comment by artamonJr** [comment]
> ![image](https://user-images.githubusercontent.com/46949445/86460672-7871ea00-bd31-11ea-83ea-d8e79a9a19ff.png)

не сделал

Граница же у футера, зачем такие извороты?)
![image](https://user-images.githubusercontent.com/46949445/86461623-f2ef3980-bd32-11ea-9d72-629f8240da95.png)

> Присмотрись внимательно, если перенесу то работать уже будет иначе.

Присмотрелся, все работает. Почему не будет?

Почему тут строка?
![image](https://user-images.githubusercontent.com/46949445/86462522-66457b00-bd34-11ea-9fbd-ac07b43032b4.png)

> Не подтягивается )

Не подтягивается, верно) Из-за того, что ты сделал запутанный код)
Ты переопределяешь line-height в то же значение - 1. Но, самое главное, ты неявно сбрасываешь font-weight в normal. Мне пришлось потратить время, чтобы вспомнить, что если в font не задать значения св-вам, то они ставятся по умолчанию. Нужно стараться писать максимально простой код.
У нас в стандартах есть пункт по этому поводу кстати.
Посмотри и сравни, какой вариант проще для понимания?
![image](https://user-images.githubusercontent.com/46949445/86463172-aeb16880-bd35-11ea-9794-7784eb1289a6.png)

С картинками беда какая-то. Попробуй поиграться с обновлением страницы, то нормально все, то вот так
![image](https://user-images.githubusercontent.com/46949445/86465325-11a4fe80-bd3a-11ea-8b2a-570b874d5cec.png)

> И так, tabindex я как раз наоборот установил, семантический тэг не подходит так как это скорее всего будет input ratio,
а кнопки по стандартам оборачиваем в form.

Почему radio? Мне кажется, что radio тут не к месту и больше похоже на компонент состоящий из кнопок

Поправь название
![image](https://user-images.githubusercontent.com/46949445/86466454-516ce580-bd3c-11ea-9daa-d21ce78e57d4.png)

> Этот код обрабатывает нажатие клавиши enter(если фокус на элементе) как клик, то есть имитирую поведение кнопки.

А зачем имитировать кнопку если за тебя уже реализована она в браузере?

**Comment by AkhmadBabaev** [comment]
> не сделал 

хм странно, помню как менял название.

> Граница же у футера, зачем такие извороты?) 
> Присмотрелся, все работает. Почему не будет?

Эта комбинация говорит о том что граница у футера будет появляться только когда сверху есть элемент, то есть если по той или иной причине избавиться от header'a то границы у footer'a не будет.

> что если в font не задать значения св-вам, то они ставятся по умолчанию. Нужно стараться писать максимально простой код.

Собственно говоря я это знаю, прошлый ревьювер требовал наоборот постоянно объединять, так что хочу не хочу 2 раза bold надо будет выставить. Но теперь ты просишь иначе надо менять.

> С картинками беда какая-то. Попробуй поиграться с обновлением страницы, то нормально все, то вот так

> Тут можно избавиться от обработчика на window, тк скрипт у тебя в конце страницы расположен и сработает, когда все дом элементы будут доступны

После того как выполнил пункт выше такое произошло, а связанно это с тем что девсервер порядке погружает стили в своём порядке. На продакшене такого не будет.

> Почему radio? Мне кажется, что radio тут не к месту и больше похоже на компонент состоящий из кнопок

На radio это очень просто делается ещё и семантично, у Вадима Макеева есть хороший видеоурок с примером.

> А зачем имитировать кнопку если за тебя уже реализована она в браузере?

Так как кнопки я использовать не могу из за вероятности создания вложенных form, остается использовать div, добавляю к диву tabindex а затем создаю обработку как у кнопки.

**Comment by artamonJr** [comment]
> На radio это очень просто делается ещё и семантично, у Вадима Макеева есть хороший видеоурок с примером.

Возможно оно так и есть, но на div'ах это точно не годится

> Так как кнопки я использовать не могу из за вероятности создания вложенных form,

Кнопки не обязательно использовать внутри форм

>  * + &-footer* говорит о том что граница у футера будет появляться только когда сверху есть элемент,

Ну окей, только сейчас, у тебя это любой элемент. Нужно сделать, чтобы это был card__data-header

> На продакшене такого нет но учитывая что внутри компонента находится плагин, странно поведение после снятия обработчика не удивительно, собственно говоря за этим я его установил.

Нужно сразу об этом было сказать. Верни обратно тогда

Фавиконку поставь из проекта вместо текущей)

**Comment by AkhmadBabaev** [comment]
> &-footer* говорит о том что граница у футера будет появляться только когда сверху есть элемент,

Сперва так и сделал, потом решил что мало ли что там будет, но в принципе лишним не будет сделаю header

> Все инпуты, селекты и другие интерактивные элементы форм должны располагаться внутри тега

У меня нет гарантии что после тебя кто-то другой потом не скажет давай в форму оборачивай или переверстывай на див'ы. Может оставим как есть ?

**Comment by artamonJr** [comment]
> У меня нет гарантий, что после тебя кто-то другой не предоставит мне это ишью со словами ты сделал не верно. Я думаю и понятно что знаний переверстать хватает, может оставим как есть ?

Даю тебе гарантию, что переделывать не заставят. Можешь отправлять ко мне, если будут проблемы.

Вот тут тоже лучше инкапсулировать стили для header'а внутри блока для header'а
![image](https://user-images.githubusercontent.com/46949445/86568730-fd4d4580-bf75-11ea-89d5-c37fa0763814.png)
Вот как это можно реализовать
![image](https://user-images.githubusercontent.com/46949445/86568908-49988580-bf76-11ea-9520-7002f4d92878.png)
И внутри объявления стилей для элемента использовать такую конструкцию
![image](https://user-images.githubusercontent.com/46949445/86568984-69c84480-bf76-11ea-9dab-d7d25b9e1e5e.png)
Так, у тебя будет на порядок легче читать стили. Можно быть уверенным, что стили для header'а, хранятся только внутри его самого

**Comment by artamonJr** [comment]
defineStart/определить звезды -  не очень хорошее название. Что значит определить? Не поймешь, пока не посмотришь в метод
![image](https://user-images.githubusercontent.com/46949445/86572008-ff65d300-bf7a-11ea-913e-81bcf5065211.png)
Этот метод ищет дом элементы, поэтому лучше отталкиваться от этого

**Comment by artamonJr** [comment]
Добавь фавиконку для safari
