### ISSUE TITLE
Подключение js и scss

### ISSUE THREAD

**Issue by imin314** [AkhmadBabaev/fsd-landing#3]
Нужно добавить автоматический импорт scss и js, чтобы не приходилось вручную прописывать пути для каждого файла.
https://github.com/AkhmadBabaev/fsd-landing/blob/914f7d88c052ec9b8a4206a58dae649abc9635ce/src/pages/index/index.scss#L21-L36

scss тоже должны импортироваться в главный js:
https://github.com/AkhmadBabaev/fsd-landing/blob/914f7d88c052ec9b8a4206a58dae649abc9635ce/src/pages/index/index.pug#L14

А он в свою очередь должен подключаться автоматически через webpack:
https://github.com/AkhmadBabaev/fsd-landing/blob/914f7d88c052ec9b8a4206a58dae649abc9635ce/src/pages/index/index.pug#L27

Стили для плагина swiper импортируй из node_modules в scss соответствующего компонента.
https://github.com/AkhmadBabaev/fsd-landing/blob/914f7d88c052ec9b8a4206a58dae649abc9635ce/src/pages/index/index.pug#L11

**Comment by AkhmadBabaev** [comment]
1. Технически я могу тут использоваться require context я использовал его в слайдере, но если меня попросят добавить ещё одну страницу где будет Js, он не годится. 

2. Разве это необходимо ? Я просто разделяю на выходе js и css файл, чтобы не грузить лишнего и улучшить кэширование. А если ты про то что webpack сам это подключает то я намеренно это изменил т.к мне нужно больше контроля. 

3. Касаемо swiper, да тут я забыл это сделать )

**Comment by imin314** [comment]
Расскажи поподробнее, пожалуйста, по первым двум пунктам. Сейчас все равно мотивация не выглядит очевидной.
1) Почему require.context помешает, если подключить еще одну страницу с js? Можно же настроить webpack так, чтобы для каждой страницы подключался свой js-файл.
2) Про какой именно контроль идет речь? В каких случаях подключение стилей и js вручную лучше, чем автоматическое?

**Comment by AkhmadBabaev** [comment]
. Представим у тебя две страницы очень разные. Чтобы не грузить в каждую страницу код с другой страницы нам на это четко разделить тут помогают две точки входа. Если использоваться require context в этих случаях мы получаем что в обе точки входа грузится js, css, поэтому на странице где вообще не используется jquery мы можем получить огромный код jqeury или swiper к примеру. Четко разделение и ручной импорт позволяют не грузить ничего лишнего, а так же контролировать порядок подключения css  если это необходимо, так как могут быть случаи что на экране во время загрузки будут странные блики так как стили обрабатываются неверно. Можно представить момент что мы добавили на странице прелоадер и нам крайне важно чтобы стили прелоадера грузились первым или критический css к примеру.
2. Про контроль уже рассказал, в require context хорошо когда у тебя только одна страница и ты грузишь все js разом вместо ручного подключения. В моём случае у меня две страницы но одна без js так что все инициализации js в компонентах связанны c страницей с карточками, так что require.c возможен но до поры до времени и к тому же на текущий момент только два импорта, даже если можно для красота сделать сейчас то смысла нет.

**Comment by imin314** [comment]
По поводу ручного импорта scss и js поняла. Думаю, на учебном проекте нормально, что они собираются вручную, если ты хочешь разграничить импорт. На крупных проектах вряд ли кто-то так делает, потому что даже в полном проекте toxin уже сложно следить за количеством компонентов и подключать каждый вручную неудобно.

Давай тогда оставим index.scss и color.scss как есть, но только я бы все-таки посоветовала удалить комментарии и оформить импорты, как в js (просто между тематическими блоками добавлять пустую строку).

Еще нужно избавиться от подобной схемы импорта в pug:
```
link(rel = "stylesheet" href = "styles/index.bundle.css") 
script(src = "scripts/index.bundle.js") 
```
Тебе нужно colors.scss импортировать в colors.js и подключать его к странице colors через вебпак. Аналогично для index.

**Comment by imin314** [comment]
Еще вот этот момент смущает:
https://github.com/AkhmadBabaev/fsd-landing/blob/914f7d88c052ec9b8a4206a58dae649abc9635ce/src/pages/colors/colors.scss#L20-L58

Сейчас у тебя импорт общих стилей, миксинов, стилей компонентов идет в одном файле со стилями для .colors-page. Чтобы этого избежать, ты можешь содержимое colors-page вынести в отдельный блок, а на странице .colors вызывать соответствующий миксин.

**Comment by AkhmadBabaev** [comment]
Комментарии на продакшене всё равно удаляются, а если я через месяц вернусь к проекту они очень кстати, так как могу забыть я продумал схему где вместо Аux.. у меня импортируются только миксины или всё же и прочее вспомогательные файлы. 
![image](https://user-images.githubusercontent.com/51095975/83628926-efd12400-a5a1-11ea-9136-1f947c38abf4.png) Запись на скрине, тоже самое что и ручной импорт css в js файл, но удобнее. Что же касается того что вебпак подключает файлы стоит отметить что я намеренно отключил такое поведение, зачем я это сделал точно сказать не могу т.к. давно пользуюсь таким шаблоном но скорее всего на то была причина. Думаю если ты начнешь использовать несколько точек входа, а так же пытаться работать на кэширование, всмысле можно сделать так чтобы весь код плагинов автоматически генерировался в файл vendor.[entrypoint].js то ты столкнешься с тем что импорт html-webpack-plugin'а не справляется )

**Comment by AkhmadBabaev** [comment]
Верно следить за всем это сложно, но в реальных проектах скорость загрузки серьезно решает, особенно требовательны могут быть заказчики с многофункциональных проектов типа toxin и в таких сайтах лишнего на разных страниц довольно таки много, чем ручной импорт серьезно помогает в скорости загрузки )

**Comment by AkhmadBabaev** [comment]
С авто импортом html webpack plugin'a появляются те же проблемы что и с require.c, так же могут быть исключения когда нужно js импортировать в шапку, вероятно всё это решается но из того что я помню решая одну проблему зарождалась из неё новая, на текушем моменте можно положиться на автоимпорта плагина но если подключать несколько страниц то выносить vendors будет хорошей мыслью, так как код плагинов обновляется очень редко, он просто кэшируется и это влияет скорость загрузки при повторных входах на страницу.

**Comment by AkhmadBabaev** [comment]
https://github.com/AkhmadBabaev/fsd-landing/issues/3#issuecomment-638119958
Вообщем я думал сделать точно так же, но не был уверен стоит ли это выносить в отдельный компонент не смотря на то что тут используется scss блок.

**Comment by imin314** [comment]
В общем сошлись с коллегами на том, что в рамках этого задания не нужно разбираться с тонкостями вебпака, поэтому ишью закрываю.
