### ISSUE TITLE
Соблюдение стандартов

### ISSUE THREAD

**Issue by imin314** [AkhmadBabaev/fsd-landing#4]
1) По стандартам airbnb в js используются одинарные кавычки. Это правило распространяется на js-код в pug:
https://github.com/AkhmadBabaev/fsd-landing/blob/914f7d88c052ec9b8a4206a58dae649abc9635ce/src/pages/index/index.pug#L4-L8

2) В html по стандартам компании ([7 пункт](https://github.com/fullstack-development/front-end-best-practices/blob/master/CSS/rules.md)) нужно указывать еще и цвет фона:
https://github.com/AkhmadBabaev/fsd-landing/blob/914f7d88c052ec9b8a4206a58dae649abc9635ce/src/styles/basic.scss#L1-L9
+ line-height лучше указать без единиц измерения (коэффициентом) в сокращенном свойстве font.

3) Сейчас у тебя глобально во многих свойствах используется em, но не похоже, что отступление от стандартов здесь действительно необходимо, поэтому em надо заменить на rem:
https://github.com/AkhmadBabaev/fsd-landing/blob/914f7d88c052ec9b8a4206a58dae649abc9635ce/src/components/card-data/card-data.scss#L2

4) Не используй отрицательные margin ([пункт 4](https://github.com/fullstack-development/front-end-best-practices/blob/master/CSS/rules.md)):
https://github.com/AkhmadBabaev/fsd-landing/blob/914f7d88c052ec9b8a4206a58dae649abc9635ce/src/components/price/price.scss#L6

**Comment by AkhmadBabaev** [comment]
1. В проекте слайдера я сделал как в примере выше но мне сказали что js и pug тоже должен использоваться в кавычках, тут надо разобраться.

4. Использовать rem на padding кажется не верным решением. Узнаю у Сергей есть ли ограничения на em.

5. Да, там как мне кажется ошибка в дизайне, но когда меня проверяли сказали в этот раз сделать именно по дизайну даже если есть мелкие неточности, на position тоже ограничения по стандартам стоят мне остается transform использовать но верно ли это ?

**Comment by imin314** [comment]
1. Ты можешь отправить ссылку на соответствующее ишью? Вообще по стандартам в html нужны двойные кавычки только в атрибутах ([пункт 9](https://github.com/fullstack-development/front-end-best-practices/blob/master/HTML/tags.md))

**Comment by AkhmadBabaev** [comment]
1. https://github.com/AkhmadBabaev/ordinary-slider/issues/26

2. Как бы то не было em предпочтительнее, так как padding и прочие свойства за em считают текущий размер шрифта, поэтому если у тебя есть какой то блок с текстом у которого есть иконка на каком то расстоянии от него, лучше использовать em padding т.к. когда размер текста будет меняться padding будет увеличиваться пропорционально размеру текста а не общему rem. В случае с rem будет иной результат, а так как разница особой в некоторых случаях и правда нету я использую em для padding везде на всякий.

3. Я сделал так как ты просишь У меня был онлайн кодинг и два разработчика смотрели за этим мной и попросили сделать по точнее. Но правлю, надеюсь снова переправлять не придётся.

**Comment by imin314** [comment]
1. Вообще эта правка, конечно, формальная, т. к. в реальных проектах pug не используется. Но чтобы не было недопонимания, если сам будешь заниматься ревью, то я бы все-таки остановилась на версии, когда двойные кавычки используются только в атрибутах.

2. em бывает удобнее, чем rem, согласна. Но т. к. в проектах, сверстанных по стандартам, у тебя все равно будут использоваться rem, которые меняются глобально через font-size в html, то и padding в rem будут меняться вслед за размером шрифта. Также следует понимать, что текущий размер шрифта наследуется от родителя, поэтому если в родителе он задан тоже в em, то может возникнуть ситуация, описанная в [этой статье](https://learn.javascript.ru/css-units#otnositelno-shrifta-em). В проектах с компонентной архитектурой ты можешь заранее не знать, где будет использоваться твой компонент и em'ы вносят долю непредсказуемости в поведение блоков.

3. Этот пункт обсудили с коллегами. Я сперва не обратила внимание, что под макет можно подстроиться без отрицательных отступов и transform. Можно было первую строку оставить как есть, а вместо этого сдвинуть нижнюю положительным margin-right, например.
![Выделение_410](https://user-images.githubusercontent.com/40715953/83620808-0aae9300-a5b8-11ea-9bbd-5ee87b7d1bd6.png)
