### ISSUE TITLE
Шрифты

### ISSUE THREAD

**Issue by imin314** [AkhmadBabaev/fsd-landing#5]
Названия шрифтов должны быть в стиле lower-case-hyphenated (см. [пункт 1](https://github.com/fullstack-development/front-end-best-practices/blob/master/HTML/includeFiles.md)):
![Выделение_404](https://user-images.githubusercontent.com/40715953/83599753-29e8f880-a597-11ea-8c36-a9345c39f6a3.png)

Мне кажется, эти комментарии избыточны, т. к. из названий шрифтов ясно, что первый - regular, а второй - bold.
https://github.com/AkhmadBabaev/fsd-landing/blob/914f7d88c052ec9b8a4206a58dae649abc9635ce/src/styles/fonts/montserrat.scss#L3-L9

**Comment by AkhmadBabaev** [comment]
Такое именование в шрифтах было намеренно, т.к. так миксин короче выходил, решил списать это на индивидуальное соглашение. Но не проблема поправить.
