### ISSUE TITLE
Замечания по js

### ISSUE THREAD

**Issue by imin314** [AkhmadBabaev/fsd-landing#6]
1) querySelectorAll возвращает NodeList, по которому можно пройтись с помощью forEach() без каких-либо преобразований ([mdn](https://developer.mozilla.org/en-US/docs/Web/API/NodeList)):
https://github.com/AkhmadBabaev/fsd-landing/blob/914f7d88c052ec9b8a4206a58dae649abc9635ce/src/components/card/Card-init.js#L5

**Comment by AkhmadBabaev** [comment]
Верно, поправлю, на самом деле я обычно так подстраховываюсь в некоторых приходится насильно преобразовывать в обычный массив. Поправлю.
