### ISSUE TITLE
Компонент cardSlider

### ISSUE THREAD

**Issue by imin314** [AkhmadBabaev/fsd-landing#7]
1) Инициализация js для этого компонента должна происходить независимо от того, где этот блок используется. То есть схема аналогична Card-init.js - находишь все 'js-card-slider' и создаешь для них экземпляр класса CardSlider. А сейчас тебе в блоке card приходится создавать дополнительный div.js-card__slider, чтобы инициализировать свайпер:
https://github.com/AkhmadBabaev/fsd-landing/blob/914f7d88c052ec9b8a4206a58dae649abc9635ce/src/components/card/Card.js#L9-L10

2) Плагин swiper позволяет гибко настраивать имена классов для любых встроенных элементов. Когда есть такая возможность, надо ей пользоваться:) И структура компонента будет более читабельной и понятной из-за отсутствия служебных классов, которые не вписываются в БЭМ:
https://github.com/AkhmadBabaev/fsd-landing/blob/914f7d88c052ec9b8a4206a58dae649abc9635ce/src/components/card-slider/card-slider.pug#L4-L14

**Comment by AkhmadBabaev** [comment]
1. Можете обьяснить зачем глобальная инициализовация компонента card слайдер если по смыслу этот компонент как элемент связанный напрямую со card. То есть без card он смысла не имеет а так же учитывая выше упомянутый факт может появиться необходимость расширить СardSlider и использовать методы Cardslider в компоненте Card. Намекаю на то что я его и глобально инициализирую, а затем ещё и в Card инициализирую чтобы пользоваться его методами. Технически я делал такое в компонент CheckBox из проекта со слайдером, но решил что не стоит инициализировать глобально то что напрямую связанно )

**Comment by AkhmadBabaev** [comment]
![image](https://user-images.githubusercontent.com/51095975/83631295-f5c90400-a5a5-11ea-94b3-248dff4e763a.png)
В целом я пользовался настройкой имён классов если мы об одном и том же. Не стал заморачиваться более детально, но подкорректирую.

**Comment by imin314** [comment]
> 1. **CardSlider** по смыслу это компонент похожий на элемент связанный напрямую с компонентом **Сard**. То есть без card он смысла не имеет, а так же учитывая выше упомянутый факт может появиться необходимость расширить **СardSlider** и использовать методы **Cardslider** в компоненте **Card**. Намекаю на то что придётся его глобально инициализировать, а затем ещё и в **Card** инициализировать чтобы пользоваться его методами. Технически я делал такое в компоненте **CheckBox** из проекта со слайдером, но решил что не стоит инициализировать глобально то что напрямую связанно )

Сейчас у тебя в CardSlider нет никаких методов, которыми бы пользовался класс Card. И неизвестно вообще, появятся ли они в перспективе. То есть, что у нас есть сейчас:
1) Чтобы проинициализировать CardSlider нужно создавать в pug родительского блока обертку, создавать для этого блока js-класс (кроме инициализации CardSlider в Card.js ничего не происходит), и приходится явно держать в голове, какие компоненты надо инициализировать явно, какие автоматически.
2) Если я захочу добавить CardSlider в какой-нибудь другой простенький блок, то мне снова придется для него создавать js-класс, чтобы создать экземпляр CardSlider. А вероятность того, что CardSlider будет переиспользоваться, мне кажется, больше, чем добавление каких-то публичных методов в него.

**Comment by imin314** [comment]
> В целом я пользовался настройкой имён классов если мы об одном и том же. Не стал заморачиваться более детально.

Надо сделать так, чтобы в pug структура этого блока не отличалась от привычной БЭМовской:
https://github.com/AkhmadBabaev/fsd-landing/blob/77f2e7e1423ed1719eae9f209fda8dbcff8ebbc9/src/components/card-slider/card-slider.pug#L6-L10

Сейчас у тебя помимо БЭМ-классов висят на элементах классы, необходимые для работы плагина.

**Comment by AkhmadBabaev** [comment]
https://github.com/AkhmadBabaev/fsd-landing/issues/7#issuecomment-639335145
А что в этом плохого ? 
1. Мы везде используем плагины и такие классы висят не мешают вроде.
2. Эти классы носят дефолтные стили необходимые для работы слайдера, а в некоторых случаях и js код на них повязан. Выходит мне нужно удалять классы типа swiper-container и переносить стили и вероятно js в некоторых случаях, какой смысл переписывать готовый код ?

**Comment by AkhmadBabaev** [comment]
На текущий момент я избавил немного от классов которые было убрать просто, а так же в scss больше не используются классы слайдера. 
![image](https://user-images.githubusercontent.com/51095975/83863076-7e24e180-a72b-11ea-9fdd-a4f72f33f5e3.png) Дальнейшие изменения нуждаются в стилей обработке.
