### ISSUE TITLE
Избыточное деление на блоки

### ISSUE THREAD

**Issue by imin314** [AkhmadBabaev/fsd-landing#8]
В блоке card-data в хедере используются два компонента card-info и price. Содержимое этих блоков минимальное, и очевидно, что они являются частью блока card-data и не будут использоваться в отрыве от него. Поэтому, мне кажется, что нет смысла выносить их в отдельные компоненты.
![Выделение_406](https://user-images.githubusercontent.com/40715953/83602917-a7176c00-a59d-11ea-8e96-c4ee5ada02c4.png)

https://github.com/AkhmadBabaev/fsd-landing/blob/914f7d88c052ec9b8a4206a58dae649abc9635ce/src/components/card-data/card-data.pug#L5-L22

Еще почему-то переменная isLuxury нигде не используется.

**Comment by AkhmadBabaev** [comment]
Card data это более общий блок тоесть туда входит и ревью и звезды. 
![image](https://user-images.githubusercontent.com/51095975/83617225-7598a380-a591-11ea-98f9-c04c706507ad.png) У нас есть другая карточка где используется price и info а так же price технически ещё где то появиться может поэтому info и price разделены хотя можно было бы и обьединить.

**Comment by AkhmadBabaev** [comment]
Касаемо isLuxury верно, перед сдачей одно перебазирование не удачно прошло что часть инфы сплелась а я и не заметил, а так же одинаковые файлы миксинов headers.scss и titles.scss, хотя titles это переименованный headers.
