### ISSUE TITLE
layout.pug

### ISSUE THREAD

**Issue by imin314** [AkhmadBabaev/fsd-landing#9]
layout.pug не является компонентом, его лучше перенести в src. Можно в папке pages создать подпапку layout и там хранить layout.pug и общие стили из basic.scss.

**Comment by AkhmadBabaev** [comment]
Касаемо этого момента мне на слайдере так же ишью создали и я перенёс его в компоненты )

**Comment by imin314** [comment]
Ну у нас случается несогласованность по ишьюзам. Мне кажется, что layout не относится к компонентам, хотя бы потому, что он оформляется не миксином, как остальные блоки.

Его можно переиспользовать, но его содержимое очень специфическое, и в произвольном месте, как другие компоненты, ты его вставишь.

**Comment by imin314** [comment]
В общем, мы посоветовались с коллегами и думаем, что логично будет убрать его из компонентов.

**Comment by AkhmadBabaev** [comment]
Я говорил тоже самое что и ты по этому вопросу. Вместо папки pages у меня была Auxiliary куда я сбрасывал вспомогательные файлы разметки и стилей. Думаю создам Auxiliary и папку styles перенесу в неё.
